name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      
      - name: Check formatting
        working-directory: terraform
        run: terraform fmt -check -recursive
      
      - name: Init (skip backend for CI)
        working-directory: terraform
        run: terraform init -backend=false
      
      - name: Validate
        working-directory: terraform
        run: terraform validate
